import { NextResponse } from "next/server";
import bcrypt from "bcryptjs";
import { connectDB } from "@/lib/mongodb";
import Car from "@/models/Car";
import User from "@/models/User";
import CarRequest from "@/models/CarRequest";

// Working car images from Unsplash (direct image URLs, publicly accessible)
const carImages: Record<string, string[]> = {
  "Honda": [
    "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800&q=80",
    "https://images.unsplash.com/photo-1606611013016-969c19ba27d5?w=800&q=80",
  ],
  "Hyundai": [
    "https://images.unsplash.com/photo-1629897048514-3dd7414fe72a?w=800&q=80",
    "https://images.unsplash.com/photo-1625231334401-4c6ae07f0b04?w=800&q=80",
  ],
  "Maruti Suzuki": [
    "https://images.unsplash.com/photo-1549317661-bd32c8ce0afe?w=800&q=80",
    "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
  ],
  "Toyota": [
    "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800&q=80",
    "https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=800&q=80",
  ],
  "Tata": [
    "https://images.unsplash.com/photo-1617814076668-8dfc6fe3a4e0?w=800&q=80",
    "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80",
  ],
  "Mahindra": [
    "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80",
    "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
  ],
  "Kia": [
    "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80",
    "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800&q=80",
  ],
  "Volkswagen": [
    "https://images.unsplash.com/photo-1471479917193-f00955256257?w=800&q=80",
    "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80",
  ],
  "MG": [
    "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80",
    "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80",
  ],
  "BMW": [
    "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80",
    "https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800&q=80",
  ],
  "Mercedes": [
    "https://images.unsplash.com/photo-1618843479619-f3d0d81e4d10?w=800&q=80",
    "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=800&q=80",
  ],
  "Skoda": [
    "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&q=80",
    "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80",
  ],
  "default": [
    "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80",
    "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&q=80",
  ],
};

function getImages(brand: string): string[] {
  return carImages[brand] || carImages["default"];
}

const sampleCars = [
  {
    title: "Honda City 2023 VX CVT",
    brand: "Honda",
    model: "City",
    year: 2023,
    price: 1250000,
    city: "Delhi",
    fuelType: "Petrol",
    transmission: "Automatic",
    kilometers: 12000,
    ownership: "1st Owner",
    registrationState: "Delhi",
    description: "Well-maintained Honda City with full service history. Single owner, always garaged. Premium sedan with excellent mileage and comfort.",
    features: ["Sunroof", "Touchscreen Infotainment", "Rear Camera", "LED Headlights", "Cruise Control", "Keyless Entry", "Push Button Start", "Alloy Wheels", "Auto AC", "6 Airbags"],
    inspectionReport: "Engine: Excellent | Transmission: Excellent | Suspension: Good | Brakes: Excellent | Overall Score: 9.2/10",
    serviceHistory: "All services done at authorized Honda dealership.",
    images: getImages("Honda"),
  },
  {
    title: "Hyundai Creta 2022 SX(O)",
    brand: "Hyundai",
    model: "Creta",
    year: 2022,
    price: 1450000,
    city: "Mumbai",
    fuelType: "Diesel",
    transmission: "Automatic",
    kilometers: 25000,
    ownership: "1st Owner",
    registrationState: "Maharashtra",
    description: "Top-end Hyundai Creta with panoramic sunroof and ADAS features. Perfect family SUV.",
    features: ["Panoramic Sunroof", "ADAS", "Ventilated Seats", "Bose Sound System", "Wireless Charging", "360 Camera", "Connected Car Tech", "Air Purifier", "Rear AC Vents", "6 Airbags"],
    inspectionReport: "Engine: Excellent | Transmission: Excellent | Suspension: Excellent | Overall Score: 9.5/10",
    serviceHistory: "Regular servicing at Hyundai authorized center. Extended warranty active till 2027.",
    images: getImages("Hyundai"),
  },
  {
    title: "Maruti Swift 2021 ZXI+",
    brand: "Maruti Suzuki",
    model: "Swift",
    year: 2021,
    price: 650000,
    city: "Bangalore",
    fuelType: "Petrol",
    transmission: "Manual",
    kilometers: 35000,
    ownership: "1st Owner",
    registrationState: "Karnataka",
    description: "Sporty and fuel-efficient Maruti Swift. Top variant with all features. Best-in-class mileage of 22 kmpl.",
    features: ["Touchscreen", "Rear Camera", "Push Button Start", "Auto Headlights", "Steering Controls", "ABS", "EBD", "2 Airbags", "Rear Defogger", "Alloy Wheels"],
    inspectionReport: "Engine: Good | Transmission: Good | Overall Score: 8.5/10",
    serviceHistory: "Serviced every 10,000 km at Maruti ARENA.",
    images: getImages("Maruti Suzuki"),
  },
  {
    title: "Toyota Fortuner 2022 Legender",
    brand: "Toyota",
    model: "Fortuner",
    year: 2022,
    price: 4200000,
    city: "Delhi",
    fuelType: "Diesel",
    transmission: "Automatic",
    kilometers: 18000,
    ownership: "1st Owner",
    registrationState: "Delhi",
    description: "The premium Fortuner Legender with distinctive dual-tone design. Powerful 2.8L diesel engine with 4x4 capability.",
    features: ["JBL Sound System", "Wireless Charging", "Kick Sensor Tailgate", "Cooled Seats", "360 Camera", "Terrain Modes", "7 Seats", "LED DRLs", "Connected Car", "7 Airbags"],
    inspectionReport: "Engine: Excellent | Transmission: Excellent | Overall Score: 9.8/10",
    serviceHistory: "Toyota authorized service center. Complete service history available.",
    images: getImages("Toyota"),
  },
  {
    title: "Tata Nexon EV 2023 Max LR",
    brand: "Tata",
    model: "Nexon EV",
    year: 2023,
    price: 1750000,
    city: "Pune",
    fuelType: "Electric",
    transmission: "Automatic",
    kilometers: 8000,
    ownership: "1st Owner",
    registrationState: "Maharashtra",
    description: "Long range Nexon EV with 437km range. Zero emission driving with fast charging capability. 5-star safety rated.",
    features: ["Connected Car", "Ventilated Seats", "Sunroof", "Air Purifier", "Fast Charging", "Regenerative Braking", "Drive Modes", "Wireless Charging", "JBL Speakers", "6 Airbags"],
    inspectionReport: "Battery Health: 98% | Motor: Excellent | Overall Score: 9.6/10",
    serviceHistory: "Tata authorized EV service center. Battery warranty active till 2031.",
    images: getImages("Tata"),
  },
  {
    title: "Mahindra XUV700 2022 AX7 L",
    brand: "Mahindra",
    model: "XUV700",
    year: 2022,
    price: 2100000,
    city: "Hyderabad",
    fuelType: "Diesel",
    transmission: "Automatic",
    kilometers: 30000,
    ownership: "1st Owner",
    registrationState: "Telangana",
    description: "Feature-loaded XUV700 with ADAS Level 2, dual screen setup and premium interiors.",
    features: ["ADAS Level 2", "Dual 10.25\" Screens", "Alexa Built-in", "Panoramic Sunroof", "Flush Door Handles", "3D Sound", "Wireless Charging", "360 Camera", "7 Airbags"],
    inspectionReport: "Engine: Excellent | Transmission: Good | Overall Score: 9.0/10",
    serviceHistory: "Mahindra authorized service. All scheduled services completed on time.",
    images: getImages("Mahindra"),
  },
  {
    title: "Kia Seltos 2023 HTX+",
    brand: "Kia",
    model: "Seltos",
    year: 2023,
    price: 1350000,
    city: "Chennai",
    fuelType: "Petrol",
    transmission: "Automatic",
    kilometers: 15000,
    ownership: "1st Owner",
    registrationState: "Tamil Nadu",
    description: "Stylish Kia Seltos with turbocharged petrol engine. Premium interiors with connected car features.",
    features: ["10.25\" Touchscreen", "Bose Sound", "Ventilated Seats", "UVO Connected", "Sunroof", "LED Headlights", "Wireless Charger", "360 Camera", "6 Airbags"],
    inspectionReport: "Engine: Excellent | Transmission: Excellent | Overall Score: 9.1/10",
    serviceHistory: "Regular Kia authorized servicing. Warranty valid till 2028.",
    images: getImages("Kia"),
  },
  {
    title: "Volkswagen Virtus 2023 GT Plus",
    brand: "Volkswagen",
    model: "Virtus",
    year: 2023,
    price: 1650000,
    city: "Bangalore",
    fuelType: "Petrol",
    transmission: "Automatic",
    kilometers: 10000,
    ownership: "1st Owner",
    registrationState: "Karnataka",
    description: "German engineering meets Indian roads. The Virtus GT with 1.5L TSI turbo engine delivers thrilling performance.",
    features: ["Virtual Cockpit", "Wireless CarPlay", "Ventilated Seats", "Sunroof", "Auto Dimming Mirror", "Rain Sensing Wipers", "Cruise Control", "6 Airbags", "ESC"],
    inspectionReport: "Engine: Excellent | Transmission: Excellent | Overall Score: 9.4/10",
    serviceHistory: "All services at VW authorized center. Extended warranty active.",
    images: getImages("Volkswagen"),
  },
  {
    title: "Maruti Baleno 2022 Alpha CVT",
    brand: "Maruti Suzuki",
    model: "Baleno",
    year: 2022,
    price: 850000,
    city: "Delhi",
    fuelType: "Petrol",
    transmission: "Automatic",
    kilometers: 20000,
    ownership: "2nd Owner",
    registrationState: "Delhi",
    description: "Premium hatchback with spacious interiors and great fuel efficiency.",
    features: ["HUD", "360 View Camera", "9\" Touchscreen", "Arkamys Sound", "Auto AC", "LED Projector Lights", "Cruise Control", "Rear AC Vents", "6 Airbags"],
    inspectionReport: "Engine: Good | Transmission: Good | Overall Score: 8.3/10",
    serviceHistory: "Regular servicing at NEXA dealership.",
    images: getImages("Maruti Suzuki"),
  },
  {
    title: "MG Hector 2021 Sharp Pro",
    brand: "MG",
    model: "Hector",
    year: 2021,
    price: 1550000,
    city: "Mumbai",
    fuelType: "Diesel",
    transmission: "Manual",
    kilometers: 40000,
    ownership: "1st Owner",
    registrationState: "Maharashtra",
    description: "Internet car with i-SMART technology. Massive 14\" portrait touchscreen. Spacious cabin with premium feel.",
    features: ["14\" Touchscreen", "i-SMART Connected", "Panoramic Sunroof", "Infinity Sound", "Wireless Charging", "Leather Seats", "Powered Tailgate", "6 Airbags"],
    inspectionReport: "Engine: Good | Transmission: Good | Overall Score: 8.0/10",
    serviceHistory: "All services at MG authorized workshops.",
    images: getImages("MG"),
  },
  {
    title: "Hyundai i20 2023 Asta(O)",
    brand: "Hyundai",
    model: "i20",
    year: 2023,
    price: 1050000,
    city: "Kolkata",
    fuelType: "Petrol",
    transmission: "Automatic",
    kilometers: 9000,
    ownership: "1st Owner",
    registrationState: "West Bengal",
    description: "Premium hatchback with segment-best features. Sunroof, BlueLink connected tech and sportier design.",
    features: ["Sunroof", "BlueLink", "Bose Premium Sound", "10.25\" Infotainment", "Digital Cluster", "Wireless Charging", "Air Purifier", "LED Package", "6 Airbags"],
    inspectionReport: "Engine: Excellent | Transmission: Excellent | Overall Score: 9.3/10",
    serviceHistory: "Hyundai authorized service. Complete digital service history.",
    images: getImages("Hyundai"),
  },
  {
    title: "Tata Harrier 2022 XZA+",
    brand: "Tata",
    model: "Harrier",
    year: 2022,
    price: 1800000,
    city: "Pune",
    fuelType: "Diesel",
    transmission: "Automatic",
    kilometers: 28000,
    ownership: "1st Owner",
    registrationState: "Maharashtra",
    description: "Bold and beautiful Tata Harrier built on Land Rover D8 platform. Commanding road presence with 5-star safety.",
    features: ["Panoramic Sunroof", "JBL 9-speaker", "Connected Car", "Terrain Response", "Auto Park Assist", "Wireless Charging", "360 Camera", "LED DRLs", "6 Airbags"],
    inspectionReport: "Engine: Excellent | Transmission: Good | Overall Score: 8.8/10",
    serviceHistory: "Tata authorized service center. All maintenance records available.",
    images: getImages("Tata"),
  },
  {
    title: "BMW 3 Series 2021 320d Sport",
    brand: "BMW",
    model: "3 Series",
    year: 2021,
    price: 3500000,
    city: "Mumbai",
    fuelType: "Diesel",
    transmission: "Automatic",
    kilometers: 22000,
    ownership: "1st Owner",
    registrationState: "Maharashtra",
    description: "The ultimate driving machine. BMW 320d Sport Line with M Sport package. 190hp diesel engine with 8-speed automatic.",
    features: ["M Sport Package", "Live Cockpit", "Harman Kardon Sound", "Ambient Lighting", "Gesture Control", "Wireless Charging", "Head-Up Display", "Parking Assist", "6 Airbags"],
    inspectionReport: "Engine: Excellent | Transmission: Excellent | Overall Score: 9.5/10",
    serviceHistory: "BMW authorized service with full digital records.",
    images: getImages("BMW"),
  },
  {
    title: "Kia Sonet 2022 HTX+ Turbo",
    brand: "Kia",
    model: "Sonet",
    year: 2022,
    price: 1100000,
    city: "Hyderabad",
    fuelType: "Petrol",
    transmission: "Automatic",
    kilometers: 18000,
    ownership: "1st Owner",
    registrationState: "Telangana",
    description: "Compact SUV with turbo petrol engine. Feature-rich with connected car technology and bold design.",
    features: ["10.25\" Touchscreen", "Bose Sound", "Ventilated Seats", "UVO Connected", "Sunroof", "LED Headlights", "Wireless Charger", "Rear Camera", "6 Airbags"],
    inspectionReport: "Engine: Excellent | Transmission: Good | Overall Score: 8.9/10",
    serviceHistory: "Kia authorized service center. Warranty active.",
    images: getImages("Kia"),
  },
  {
    title: "Skoda Slavia 2023 Style 1.5 TSI",
    brand: "Skoda",
    model: "Slavia",
    year: 2023,
    price: 1550000,
    city: "Bangalore",
    fuelType: "Petrol",
    transmission: "Automatic",
    kilometers: 12000,
    ownership: "1st Owner",
    registrationState: "Karnataka",
    description: "Czech sedan with powerful 1.5 TSI engine and rock-solid build quality. Best-in-class driving dynamics.",
    features: ["Ventilated Seats", "Sunroof", "Wireless CarPlay", "10\" Touchscreen", "Cruise Control", "Auto AC", "LED Headlights", "6 Airbags", "ESC", "Tyre Pressure Monitor"],
    inspectionReport: "Engine: Excellent | Transmission: Excellent | Overall Score: 9.2/10",
    serviceHistory: "Skoda authorized service. Full warranty coverage.",
    images: getImages("Skoda"),
  },
  {
    title: "Toyota Innova Crysta 2022 VX",
    brand: "Toyota",
    model: "Innova Crysta",
    year: 2022,
    price: 2400000,
    city: "Chennai",
    fuelType: "Diesel",
    transmission: "Automatic",
    kilometers: 35000,
    ownership: "1st Owner",
    registrationState: "Tamil Nadu",
    description: "India's favorite MPV. The Innova Crysta VX with captain seats and premium features. Reliable and spacious.",
    features: ["Captain Seats", "Roof-Mounted AC", "Touchscreen", "Cruise Control", "Auto Headlights", "7 Seats", "LED DRLs", "Rear Camera", "7 Airbags"],
    inspectionReport: "Engine: Excellent | Transmission: Good | Overall Score: 9.0/10",
    serviceHistory: "Toyota authorized service with complete log.",
    images: getImages("Toyota"),
  },
  {
    title: "Honda Amaze 2023 VX CVT",
    brand: "Honda",
    model: "Amaze",
    year: 2023,
    price: 920000,
    city: "Ahmedabad",
    fuelType: "Petrol",
    transmission: "Automatic",
    kilometers: 11000,
    ownership: "1st Owner",
    registrationState: "Gujarat",
    description: "Compact sedan with class-leading boot space and smooth CVT. Honda reliability at an affordable price.",
    features: ["8\" Touchscreen", "Rear Camera", "LED Headlights", "Push Button Start", "Auto AC", "Cruise Control", "2 Airbags", "ABS", "EBD"],
    inspectionReport: "Engine: Excellent | Transmission: Excellent | Overall Score: 9.0/10",
    serviceHistory: "Honda authorized dealer servicing.",
    images: getImages("Honda"),
  },
  {
    title: "Mercedes-Benz C-Class 2022 C200",
    brand: "Mercedes",
    model: "C-Class",
    year: 2022,
    price: 5200000,
    city: "Delhi",
    fuelType: "Petrol",
    transmission: "Automatic",
    kilometers: 15000,
    ownership: "1st Owner",
    registrationState: "Delhi",
    description: "The all-new W206 C-Class with MBUX infotainment and luxurious interiors. A baby S-Class in every sense.",
    features: ["MBUX System", "11.9\" Portrait Display", "Burmester Sound", "Digital Headlights", "Ambient Lighting", "Air Suspension", "Head-Up Display", "Wireless Charging", "9 Airbags"],
    inspectionReport: "Engine: Excellent | Transmission: Excellent | Overall Score: 9.7/10",
    serviceHistory: "Mercedes-Benz Star Service with complete history.",
    images: getImages("Mercedes"),
  },
  {
    title: "Mahindra Thar 2023 LX Hard Top",
    brand: "Mahindra",
    model: "Thar",
    year: 2023,
    price: 1650000,
    city: "Jaipur",
    fuelType: "Diesel",
    transmission: "Manual",
    kilometers: 14000,
    ownership: "1st Owner",
    registrationState: "Rajasthan",
    description: "The iconic Thar with modern features. Hard-top variant with 4x4 for serious off-roading. Adventure-ready SUV.",
    features: ["4x4", "Touchscreen", "Drizzle Lights", "Roll Cage", "Adventure Statistics", "Cruise Control", "Rear Camera", "2 Airbags", "ABS", "ESP"],
    inspectionReport: "Engine: Excellent | Chassis: Excellent | 4WD System: Excellent | Overall Score: 9.3/10",
    serviceHistory: "Mahindra authorized service. All off-road checks completed.",
    images: getImages("Mahindra"),
  },
  {
    title: "Volkswagen Taigun 2022 GT Plus",
    brand: "Volkswagen",
    model: "Taigun",
    year: 2022,
    price: 1700000,
    city: "Kolkata",
    fuelType: "Petrol",
    transmission: "Automatic",
    kilometers: 19000,
    ownership: "1st Owner",
    registrationState: "West Bengal",
    description: "German-engineered compact SUV with 1.5 TSI turbo engine. Active cylinder technology for efficiency. Solid build quality.",
    features: ["Virtual Cockpit", "Wireless CarPlay", "Ventilated Seats", "Sunroof", "Connected Car", "Auto Dimming Mirror", "Rain Sensing Wipers", "6 Airbags", "ESC"],
    inspectionReport: "Engine: Excellent | Transmission: Excellent | Overall Score: 9.1/10",
    serviceHistory: "Volkswagen authorized service. Warranty valid.",
    images: getImages("Volkswagen"),
  },
];

export async function POST() {
  await connectDB();

  // Clear existing data
  await Promise.all([
    Car.deleteMany({}),
    User.deleteMany({}),
    CarRequest.deleteMany({}),
  ]);

  // Create admin user
  const hashedAdmin = await bcrypt.hash("admin123", 12);
  const adminUser = await User.create({
    name: "Admin",
    email: "admin@carplatform.com",
    password: hashedAdmin,
    role: "admin",
    city: "Delhi",
  });

  // Create 5 demo users
  const userPassword = await bcrypt.hash("user123", 12);
  const demoUsers = await User.insertMany([
    { name: "Rahul Sharma", email: "rahul@example.com", password: userPassword, role: "user", city: "Mumbai" },
    { name: "Priya Patel", email: "priya@example.com", password: userPassword, role: "user", city: "Bangalore" },
    { name: "Amit Singh", email: "amit@example.com", password: userPassword, role: "user", city: "Delhi" },
    { name: "Sneha Gupta", email: "sneha@example.com", password: userPassword, role: "user", city: "Chennai" },
    { name: "Vikram Reddy", email: "vikram@example.com", password: userPassword, role: "user", city: "Hyderabad" },
  ]);

  // Insert 20 cars
  await Car.insertMany(sampleCars);

  // Create sample car requests
  await CarRequest.insertMany([
    {
      name: "Rahul Sharma",
      email: "rahul@example.com",
      phone: "9876543210",
      brand: "Toyota",
      model: "Fortuner",
      budget: 4000000,
      fuelType: "Diesel",
      transmission: "Automatic",
      preferredYear: 2022,
      city: "Mumbai",
      message: "Looking for a white Fortuner Legender, preferably under 20k km.",
      userId: demoUsers[0]._id,
      status: "pending",
    },
    {
      name: "Priya Patel",
      email: "priya@example.com",
      phone: "9876543211",
      brand: "Hyundai",
      model: "Creta",
      budget: 1500000,
      fuelType: "Petrol",
      transmission: "Automatic",
      preferredYear: 2023,
      city: "Bangalore",
      message: "Need a top-end Creta with sunroof. White or silver preferred.",
      userId: demoUsers[1]._id,
      status: "sourcing",
    },
    {
      name: "Amit Singh",
      email: "amit@example.com",
      phone: "9876543212",
      brand: "BMW",
      model: "3 Series",
      budget: 3500000,
      fuelType: "Diesel",
      transmission: "Automatic",
      preferredYear: 2021,
      city: "Delhi",
      message: "Interested in BMW 320d or 330i. M Sport package preferred.",
      userId: demoUsers[2]._id,
      status: "found",
    },
    {
      name: "Sneha Gupta",
      email: "sneha@example.com",
      phone: "9876543213",
      brand: "Tata",
      model: "Nexon EV",
      budget: 1800000,
      fuelType: "Electric",
      transmission: "Automatic",
      preferredYear: 2023,
      city: "Chennai",
      message: "Looking for Nexon EV Max with long range. Any color is fine.",
      userId: demoUsers[3]._id,
      status: "pending",
    },
    {
      name: "Vikram Reddy",
      email: "vikram@example.com",
      phone: "9876543214",
      brand: "Mahindra",
      model: "Thar",
      budget: 1700000,
      fuelType: "Diesel",
      transmission: "Manual",
      preferredYear: 2023,
      city: "Hyderabad",
      message: "Want a hard-top Thar in black or green color. Must be 4x4.",
      userId: demoUsers[4]._id,
      status: "delivered",
    },
  ]);

  return NextResponse.json({
    message: "Database seeded successfully!",
    data: {
      admin: { email: "admin@carplatform.com", password: "admin123" },
      users: 5,
      cars: sampleCars.length,
      carRequests: 5,
    },
  });
}
